spring:
  application:
    name: rolservice
  datasource:
    url: jdbc:mariadb://localhost:3306/midatabase
    username: miusuario
    password: miclave
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

# Opcional: configuración del puerto del servidor Spring Boot
server:
  port: 8080